### ISSUE TITLE
import cv2 fails with CUDA 8.0

### ISSUE THREAD

**Issue by ProgramItUp** [kendricktan/suiron#5]
So, I updated tensorflow to r0.11, which required upgrading to CUDA 8.0 to be able to use the prebuilt Tensorflow binary for Ubuntu/Linux 64-bit, GPU enabled, Python 2.7.

Tensorflow runs correctly but 
`python ./suiron/train.py`
`import cv2 `
fails with
`Traceback (most recent call last):
  File "./train.py", line 5, in <module>
    from suiron.utils.datasets import get_servo_dataset
  File "/data/home/me/my_tensorflow/suiron/suiron/suiron/utils/datasets.py", line 9, in <module>
    from suiron.utils.img_serializer import deserialize_image
  File "/data/home/mer/my_tensorflow/suiron/suiron/suiron/utils/img_serializer.py", line 5, in <module>
    import cv2
ImportError: libcudart.so.7.5: cannot open shared object file: No such file or directory`

I spent a lot of time looking for a version of cv built against CUDA 8 but did not find anything.  
Any thoughts on the best way to resolve?

**Comment by kendricktan** [comment]
Unfortunately I have no affiliates with CUDA/OpenCV, the only thing I would recommend is to install an older version of CUDA

**Comment by arpit1997** [comment]
There are compatibility issues with opencv and CUDA 8.0. I found a solution in opencv repo

> For everyone else having this problem, here is the solution from thrust issue#800 proposed by @bramton
clone: https://github.com/thrust/thrust.git
and replace the thrust folder from CUDA 8 toolkit with the one from thrust 1.8.3 branch you cloned.
Nvidia told User @bramton They already fixed the issue and we will get the official fix with the next version of cuda 8 toolkit
I will comment again when I checked if everything works.

Try if it works :smile:

**Comment by patricio-astudillo** [comment]
(sudo) pip install opencv-python did the trick for me

**Comment by chenjxthu** [comment]
thinks, it just worked for me, too
